# Generated by Django 4.1.4 on 2022-12-19 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(help_text='Введите название категории', max_length=200, unique=True, verbose_name='Название')),
                ('cat_create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='TgAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=100, verbose_name='Имя админа')),
                ('admin_id', models.PositiveBigIntegerField(help_text='⚠Прежде чем добавлять аккаунт админа убедитесь что из этого аккаунта нажали старт на бота⚠', unique=True, verbose_name='Айди админа')),
                ('admin_created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Админы в телеграме',
                'verbose_name_plural': 'Админы в телеграме',
            },
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_firstname', models.CharField(max_length=200, verbose_name='Никнейм')),
                ('user_id', models.PositiveBigIntegerField(unique=True, verbose_name='Телеграмм айди')),
                ('user_phone', models.CharField(max_length=20, unique=True, verbose_name='Номер')),
                ('user_username', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя пользователья')),
                ('user_is_referral', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Реферал')),
                ('user_referrals_count', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество рефералов')),
                ('user_referrals_balance', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Доход с рефералов')),
                ('is_banned', models.BooleanField(default=False, verbose_name='Заблокировать')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(help_text='Введите название товара', max_length=500, verbose_name='Название')),
                ('prod_descr', models.TextField(help_text='Введите Описание товара', verbose_name='Описание')),
                ('prod_photo', models.ImageField(help_text='Загрузите фото товара', upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('prod_price', models.PositiveBigIntegerField(default=0, help_text='Укажите цену товара', verbose_name='Цена')),
                ('prod_quantity', models.PositiveIntegerField(default=0, help_text='Укажите количество товара', verbose_name='Количество')),
                ('prod_create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('prod_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_delivery_type', models.CharField(choices=[('Доставка', 'Доставка'), ('Сомавывоз', 'Сомавывоз')], max_length=10, verbose_name='Тип доставки')),
                ('order_pay_type', models.CharField(choices=[('Наличными', 'Наличными'), ('Оплата в боте', 'Оплата в боте')], max_length=20, verbose_name='Тип оплаты')),
                ('order_address', models.TextField(blank=True, null=True, verbose_name='Адрес ')),
                ('order_prod_quan', models.PositiveBigIntegerField(verbose_name='Количество')),
                ('order_create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('order_prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop_app.product', verbose_name='Товар')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop_app.tguser', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
