# Generated by Django 4.1.4 on 2022-12-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='user_phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Номер'),
        ),
    ]
