# Generated by Django 4.1.4 on 2022-12-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_remove_tguser_user_phone_order_order_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgadmin',
            name='admin_id',
            field=models.PositiveBigIntegerField(help_text='⚠ Прежде чем нажать старт на бота убедитесь что добавили аккаунт админа ⚠', unique=True, verbose_name='Айди админа'),
        ),
    ]
