# Generated by Django 4.1.4 on 2022-12-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_alter_tgadmin_admin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prod_quantity',
        ),
    ]
