# Generated by Django 4.1.4 on 2022-12-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_remove_product_prod_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_delivery_type',
            field=models.CharField(choices=[('Доставка', 'Доставка'), ('Самовывоз', 'Самовывоз')], max_length=10, verbose_name='Тип доставки'),
        ),
    ]
