# Generated by Django 4.1.4 on 2022-12-29 07:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_order_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=100, unique=True, verbose_name='Токен бота')),
                ('bot_name', models.CharField(max_length=100, unique=True, verbose_name='Название бота')),
                ('code', models.UUIDField(db_index=True, default=uuid.uuid4)),
            ],
            options={
                'verbose_name': 'Список ботов',
                'verbose_name_plural': 'Добавит бота',
            },
        ),
    ]
