# Generated by Django 4.1.4 on 2022-12-29 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0010_rename_code_tgbot_bot_code_tgbot_bot_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tgbot',
            options={'verbose_name': 'Добавит бота', 'verbose_name_plural': 'Список ботов'},
        ),
    ]
