# Generated by Django 4.1.4 on 2022-12-29 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0012_alter_tgbot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tgbot',
            options={'verbose_name': 'бота', 'verbose_name_plural': 'Добавит бота'},
        ),
    ]
