# Generated by Django 4.1.4 on 2022-12-29 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0013_alter_tgbot_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Процент от рефералов')),
                ('min_sum', models.PositiveBigIntegerField(verbose_name='Минимальная сумма для вывода')),
            ],
            options={
                'verbose_name': 'Процент от рефералов',
                'verbose_name_plural': 'Процент от рефералов',
            },
        ),
    ]
