# Generated by Django 4.1.4 on 2022-12-29 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0014_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percent',
            name='min_sum',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Минимальная сумма для вывода'),
        ),
    ]
